DROP DATABASE IF EXISTS ema_db;
CREATE DATABASE ema_db;

USE ema_db;

CREATE TABLE departments (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
department_name VARCHAR(30) NOT NULL,
department_budget INT NOT NULL,
date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
last_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE roles (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INT NOT NULL,
date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
last_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
FOREIGN KEY (department_id)
REFERENCES department(id)
ON DELETE SET NULL
);

CREATE TABLE employees (
id INT AUTO_INCREMENT
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT NOT NULL,
active_employee BOOLEAN DEFAULT true NOT NULL,
date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
last_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
FOREIGN KEY (role_id)
REFERENCES roles(id)
ON DELETE SET NULL
FOREIGN KEY (manager_id)
REFERENCES employees(id)
ON DELETE SET NULL
);


